### PR TITLE
[CVSRP-4773] update content on has employeee been on statutory leave …

### PR DESCRIPTION
**Pull request by peckoverHMRC**
…page

### CODE REVIEW

**Comment by peckoverHMRC** [comment]
Screenshot 2021-03-22 at 14 42 59

**Comment by peckoverHMRC** [comment]
inset text is to be added as part of CVSRP-4770

**Comment by LewisMitchell** [comment]
image

With inset text.

**Review by LewisMitchell — APPROVED** [review]
LGTM.

**Pull request merged**
